- README.md
Update the "Removing a column" section to include details on the `ActiveRecord::Base.ignored_columns` method that landed in https://github.com/rails/rails/pull/21720.
> Leverage Rails 5 ignored_columns

- README.md
PR for https://github.com/ankane/strong_migrations/issues/14 .
[#in_batches](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-in_batches) makes batch makes batch processing a bit cleaner.
Honestly not sure its worth cluttering up the snippet to add this, and since the method was only added in rails 5 I don't think it should replace the previous example.
Feel free to reject this PR. I'm pretty enthusiastic about #in_batches but that seems tangential to the concern of safe migrations.
> Add #in_batches code example for Rails 5+ batch processing.

- README.md
- lib/strong_migrations/migration.rb
The algorithm for adding a column with a default will miss rows added after the backfill completes (step 3) and before the column default is set (step 4). This can be fixed by setting the column default before backfilling values.
> Fix race condition in algorithm for adding a column with a default

- lib/strong_migrations/migration.rb
This PR updates the error message for removing columns to be consistent with the README changes introduced in https://github.com/ankane/strong_migrations/pull/13.
> Make error message for removing columns consistent with README

- lib/tasks/strong_migrations.rake
If `PostGISAdapter` is defined patch columns method with `StrongMigrations::AlphabetizeColumns` module.
PostGIS [includes](https://github.com/rgeo/activerecord-postgis-adapter/blob/master/lib/active_record/connection_adapters/postgis_adapter.rb#L39) their own schema statements which override the default columns implementation from Rails.
> PostGISAdapter enhancements

- README.md
- lib/strong_migrations.rb
- lib/strong_migrations/checker.rb
- lib/strong_migrations/version.rb
Allows setting `StrongMigrations.target_postgresql_version` in an initializer that will override the local `postgresql_version` check. 
As described in https://github.com/ankane/strong_migrations/issues/75
> Allow setting StrongMigrations.target_postgresql_version

- README.md
- lib/strong_migrations/checker.rb
If the model you're adding a column to has a default_scope (e.g. w/ soft deletion), the code to backfill won't update all rows. This can become a problem if you need to perform an unscoped query in the app and the default column is not set. This PR makes it so that **all** rows are updated.
- Add `unscoped` to backfill code
Given the following migration...
```rb
class AddDefaultColumn < ActiveRecord::Migration[5.0]
def change
add_column :users, :x, :string, default: '3'
end
end
```
...it now reports the following message:
```
== 20190530211525 AddDefaultColumn: migrating =================================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:
=== Dangerous operation detected #strong_migrations ===
Adding a column with a non-null …
```
> Backfill code should be unscoped

- README.md
- lib/strong_migrations.rb
- lib/strong_migrations/checker.rb
- test/strong_migrations_test.rb
* This is preferable since it avoids the extra line
* This is not currently detected and triggers a false positive
> Support and encourage adding concurrently as an option to add_reference

- lib/strong_migrations/checker.rb
- test/strong_migrations_test.rb
> Fix migration class name when displaying hints

- lib/strong_migrations.rb
- lib/strong_migrations/checker.rb
- lib/strong_migrations/migration_helpers.rb
- test/migration_helpers_test.rb
This method is not needed for mysql. So should this be a no-op for mysql or is it enough that only postgres is mentioned for foreign keys section in readme?
> Add add_foreign_key_concurrently migration helper

- lib/strong_migrations/checker.rb
- test/strong_migrations_test.rb
Postgres expects a number argument for statement and lock timeouts to be
in milliseconds. This results in the recently released migration-specific
timeouts being shorter than intended if the user sets them with
`StrongMigrations.statement_timeout=` and `.lock_timeout=`, as PG
interprets seconds as milliseconds.
This change updates the checker to multiply the submitted value by 1,000 
if the database is PG.
PG docs:
https://www.postgresql.org/docs/11/runtime-config-client.html
Co-authored-by: Susanna Kosonen <kosonen.susanna@gmail.com>
> Set Postgres statement and lock timeouts in milliseconds

- Gemfile
- lib/strong_migrations/database_tasks.rb
This PR concerns only rails app with minimum version 7, or said other way with ActiveRecord 7 minimum. 
This aims at fixing the multi db handling with the 'new' migrate method that can now have one argument => `version`
👉  https://github.com/rails/rails/blob/main/activerecord/lib/active_record/tasks/database_tasks.rb#L272
> update database_tasks for active record 7

- README.md
- lib/strong_migrations.rb
- lib/strong_migrations/checker.rb
- test/change_column_null_test.rb
Discussion: https://github.com/ankane/strong_migrations/pull/175
This PR allows setting NOT NULL on MySQL.
If any of the following conditions meets, migration will be aborted:
* MySQL is older then 5.6 (Online DDL is supported on MySQL 5.6 or later)
* MariaDB is older then 10.0 (Online DDL is supported on MariaDB 5.6 or later)
* strict mode is not enabled
* default value is set
> Allow setting NOT NULL on MySQL with online DDL.

- lib/tasks/strong_migrations.rake
I was snooping to learn how AlphabetizeColumns works, and tried the commented link. But looks like the date is one off.
https://www.pgrs.net/2008/03/13/alphabetize-schema-rb-columns/ leads to a 404 page
https://www.pgrs.net/2008/03/12/alphabetize-schema-rb-columns/ leads to the blog post.
> Link to working blog post

- lib/strong_migrations/checks.rb
- lib/strong_migrations/error_messages.rb
This gem raises an error for an explicit null default value since https://github.com/ankane/strong_migrations/issues/199.
The error message is the same as the non-null's one. But there are differences between null and non-null messages.
* The message for non-null says, `Adding a column with a **non-null** default blocks writes while the entire table is rewritten`. It is not appropriate for null default.
* The message displays `change_column_default :table, :column, nil`. It is unnecessary for null default.
* This message displays how to backfill. It is unnecessary too.
Update the error message for null default. There are many differences, so I defined a new key for the message.
I'm not sure how to test this change. I couldn't find any tests to assert error messages, so I didn't add a test …
> Improve error message on `add_column ..., default: nil`

- CHANGELOG.md
- README.md
- lib/strong_migrations/adapters/abstract_adapter.rb
- test/misc_test.rb
It is very WIP. It currently only allows to set different database versions via
```ruby
StrongMigrations.target_version = { primary: 10, animals: 11 }
```
Considerations:
* Proper testing needs to be added.
* I think, we should also allow other existing configurations to be extended to support multiple databases. There are 2 approaches I'm thinking about:
1) via hashes
```ruby
StrongMigrations.target_version = {primary: 10, animals: 11}
StrongMigrations.start_after = {primary: 20170101000000, animals: 20170101000123}
``` 
2) via methods calling
```ruby
StrongMigrations.primary.target_version = 10
StrongMigrations.animals.target_version = 11
StrongMigrations.primary.start_after = 20170101000000
StrongMigrations.animals.start_after = 20170101000123
```
* I haven't found a better way to …
> Support multiple databases for `target_version`

- lib/strong_migrations/safe_methods.rb
- test/migrations/add_reference.rb
- test/safe_by_default_test.rb
This will handle for example `foreign_key: { to_table: :table_name, on_delete: :nullify }`
> Add foreign key options to safe_add_reference

- README.md
In the "Renaming a table" section.
> Add missing "the" in README.md [skip ci]

- lib/strong_migrations/checker.rb
Following up on this Issue: https://github.com/ankane/strong_migrations/issues/255
> Disabled databases will still run the migration

- lib/generators/strong_migrations/templates/initializer.rb.tt
- lib/strong_migrations.rb
- lib/strong_migrations/adapters/abstract_adapter.rb
- lib/strong_migrations/adapters/postgresql_adapter.rb
- lib/strong_migrations/checker.rb
PG17 supports [transaction_timeout](https://postgresqlco.nf/doc/en/param/transaction_timeout/). Our application has set a relatively short value for this, as we have for statement_timeout. 
StrongMigrations changes the statement timeout to a large value. This is useless if the transaction_timeout itself remains low:
> The limit applies both to explicit transactions (started with BEGIN) and to an implicitly started transaction corresponding to a single statement.
—> StrongMigrations needs to override it to a larger value for migrations to pass.
I have not added any tests so far. Please let me know if there is something specific you would like me to test.
> support transaction_timeout (introduced in PG17)

- lib/strong_migrations/checker.rb
- lib/strong_migrations/migrator.rb
- test/migrations/timeouts.rb
- test/timeouts_test.rb
Hello,
I was running into this issue with the transaction timeout in Postgres that it need to be set before opening the transaction to actually apply (upstream [bug report](https://www.postgresql.org/message-id/554670a7-7560-4d18-8ecb-8518fddf2b9d%40app.fastmail.com)). 
I suggest the way to go to be to set that timeout in the `ddl_transaction` before the transaction opens. The test I added indeed fails without the changes to `lib/`. 
Happy to get your feedback on the strategy
> Set transaction_timeout before opening the transaction
